workflows:
  vendor-app-workflow:
    name: Vendor App Workflow
    environment:
      flutter: stable
      java: 17
      android_signing:
        - senteclick
    scripts:
      - rm -rf ~/.gradle/caches/transforms-*
      - rm -rf ~/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin
      - cd android && ./gradlew clean && cd ..
      - flutter clean
      - flutter pub get
      - flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk   # ← captures the default release APK