org.gradle.jvmargs=-Xmx6g -Xms2g -Dfile.encoding=UTF-8 -Dorg.gradle.daemon=false
android.useAndroidX=true
android.enableJetifier=false
android.builder.aapt2DaemonHeapSize=2048
kotlin.compiler.execution.strategy=in-process
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configureondemand=true
systemProp.https.protocols=TLSv1.2,TLSv1.3
systemProp.jdk.tls.client.protocols=TLSv1.2,TLSv1.3
kotlin.jvm.target.validation.mode=WARNING